### ISSUE TITLE
Typecast error when clicking Default

### ISSUE THREAD

**Issue by sdas-tech** [DJB9k/EWS-Editor-for-D365#1]
I get the following errors when clicking 'Default' for Autodiscover Email:

```
Exception details:
Message: Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' to type 'System.DirectoryServices.AccountManagement.UserPrincipal'.
Type: System.InvalidCastException
Source: System.DirectoryServices.AccountManagement
Stack Trace:
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.get_Current()
   at EWSEditor.Forms.ServiceDialog.btnDefaultSmtp_Click(Object sender, EventArgs e) in C:\Users\debrau\Documents\Visual Studio 2015\Projects\EWS Editor 3\EWS Editor\EWSEditorForDynamics365\MAIN-FEATURE\Forms\Dialogs\ServiceDialog.cs:line 497
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I also get this when clicking 'Discover' on User Name:

```
Exception details:
Message: Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' to type 'System.DirectoryServices.AccountManagement.UserPrincipal'.
Type: System.InvalidCastException
Source: System.DirectoryServices.AccountManagement
Stack Trace:
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.get_Current()
   at EWSEditor.Forms.ServiceDialog.btnDefaultUserNameSmtp_Click(Object sender, EventArgs e) in C:\Users\debrau\Documents\Visual Studio 2015\Projects\EWS Editor 3\EWS Editor\EWSEditorForDynamics365\MAIN-FEATURE\Forms\Dialogs\ServiceDialog.cs:line 611
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

I am using 1.3.16.28356

**Comment by DJB9k** [comment]
Thank you for the bug report. I'm unable to reproduce the issue in a few different environments. Can you share a few of your environment details? .Net framework version, windows version, domain, user, etc.

In the meantime, I've added better error handling for this scenario.
